/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin.delivery'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedDeliveryIndexRouteImport } from './routes/_authenticated/delivery.index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/admin/delivery',
    path: '/admin/delivery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryIndexRoute =
  AuthenticatedDeliveryIndexRouteImport.update({
    id: '/delivery/',
    path: '/delivery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/reset-password'
    | '/checkout'
    | '/favorites'
    | '/profile'
    | '/product/$id'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/orders/$id'
    | '/admin/'
    | '/delivery/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/reset-password'
    | '/checkout'
    | '/favorites'
    | '/profile'
    | '/product/$id'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/orders/$id'
    | '/admin'
    | '/delivery'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/reset-password'
    | '/_authenticated/checkout'
    | '/_authenticated/favorites'
    | '/_authenticated/profile'
    | '/product/$id'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/orders/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/delivery/'
    | '/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  MenuRoute: typeof MenuRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery/': {
      id: '/_authenticated/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof AuthenticatedDeliveryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDeliveryIndexRoute: typeof AuthenticatedDeliveryIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDeliveryIndexRoute: AuthenticatedDeliveryIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  MenuRoute: MenuRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
